### ISSUE TITLE
local.css issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#11]
- Indentation is inconsistent in `local.css`.  Please indent properties with one tab only.
- `blockquote.sign` does not need a text-indent property, because text is not indented in the `blockquote` tag.
- `<blockquote>` requires a descendant block element, usually `<p>`.  Please make sure chapter 13 has that.  It would be correct to style that `<p>` tag with `text-indent: 0;`.

**Comment by drgrigg** [comment]
Indentation fixed. (Problem was the Atom editor was set to use 'soft' tabs, ie spaces rather than tab character, I've now changed the setting). 

Fixed blockquote, created nonindented class for <p> for this sign (this sign has been more trouble than it's worth!).

**Comment by acabal** [comment]
Don't create a `.noindent` class; remember, we assign classes based on *what we're styling*, not *the resulting style*.  This is an important concept for the semantics in our ebooks.

In fact you don't need to add a class at all; instead, you can do `blockquote.sign > p` which achieves the same result and doesn't require useless and unsemantic styling cruft in the HTML.

**Comment by drgrigg** [comment]
OK, sorry. But I'm learning all the time! Fixed this now. I hope!
