### ISSUE TITLE
Stray ID attribute in chapter 8

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#12]
In `chapter-8.xhtml` line 42 the `<p>` tag has `id="top"`.  This doesn't seem to be referenced anywhere else.  Please remove it, and you should search the rest of the files for more stray IDs.  Since this ebook has no endnotes and I assume has no strange exceptions, there should be no IDs on any `<p>` tags at all.

**Comment by drgrigg** [comment]
Fixed this one, can't find any others anywhere.
