### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#2]
- `<dc:subject>` must be from LoC subject classes.  See the Gutenberg page's bibrec tab and copy and paste from there.
- `<dc:subject>` requires the `<meta property="meta-auth">` accompanying tag pointing back to the Gutenberg page from which you sourced the classifications
- All Gutenberg links must be HTTPS
- `<dc:description>` must be a complete sentence or two, not a fragment
- `se:long-description must be escaped HTML, and it must be at least a paragraph describing the work and any important contextual historical information.  Think like a Wikipedia article.  Wrap in <![CDATA[ ... ]]> and then run the `clean` tool to auto-escape all of the HTML.  See any other `content.opf` file for an example.
- `<dc:source>` must be a complete Gutenberg link to the ebook's homepage. (Not a link to the HTML file itself)
- Add `<dc:source>` for page scans
- `<meta property="se:url.encyclopedia.wikipedia">` for the book must point to a specific page about the book, otherwise remove it if no such page exists
- Artist `file-as` info is still old info, update to new artist
- Remove transcriber homepage links if none exist
- Update `<spine>` to new filenames (see other issue)

**Comment by drgrigg** [comment]
- <dc:subject> must be from LoC subject classes. See the Gutenberg page's bibrec tab and copy and paste from there.

Done.

- <dc:subject> requires the <meta property="meta-auth"> accompanying tag pointing back to the Gutenberg page from which you sourced the classifications

Done.

- All Gutenberg links must be HTTPS

Done. Also fixed these in colophon and imprint.

Have not yet committed these. See further comments about other issues.

**Comment by drgrigg** [comment]
- <dc:description> must be a complete sentence or two, not a fragment
- se:long-description must be escaped HTML, and it must be at least a paragraph describing the work and any important contextual historical information. Think like a Wikipedia article. ... See any othercontent.opf` file for an example.

Can you point me to good examples? I've downloaded already-published several Standard Ebooks so far and looked at the content.opf files, but none so far even include se:long-description ("Room With A View", "Magnificent Ambersons", "Sons and Lovers"), and all their <dc:description> tags are similar to mine, though I guess I could expand mine a little.

**Comment by acabal** [comment]
When looking at the source you shouldn't download the actual epubs from the site, because they are processed for compatibility with different ereaders so they don't reflect the actual source.  Instead, find the source on our Github organization page.  For an example of long-descriptions see https://github.com/standardebooks/booth-tarkington_the-magnificent-ambersons/blob/master/src/epub/content.opf

Your regular description can be just a sentence, but it has to be a complete sentence that somehow summarizes the work and not a sentence fragment.

**Comment by drgrigg** [comment]
I've now done all of these. Of course you should run your eye over the descriptions I've written. Thanks for your link to the source of The Magnificent Ambersons, which was very helpful.

Regarding the <dc:subject>, the only subject listed on the Bibliorec page in Gutenberg is 'Science fiction'. Looking at Ambersons, it doesn't seem as though the "PS: Literature : American and Canadian Literature" line goes in a subject field?

**Comment by acabal** [comment]
- Please use `<i>` tags for the work title in the long description.  `<em>` indicates emphasis, like shouting, which is not what we're doing when we italicize work titles.
- Long description must use curly quotes, please put those in.  Also make sure to be consistent with use of double quotes vs. single quotes.  'cosmic computer' in the last paragraph is not double-quoted as it should be.
- Run `clean` one more time to canonicalize the long-description into HTML entities to match the style in content.opf.
