### ISSUE TITLE
colophon.xhtml issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#7]
- Change "was published in 1963 by Ace Books, Inc." to "was published in 1963 by"
- You mention distributed proofreaders in the colophon, but not `content.opf`.  If they're actually part of the Gutenberg credits line, then they must be included in `content.opf`.  See https://github.com/standardebooks/algis-budrys_short-fiction/blob/master/src/epub/content.opf for an example of PGDP metadata.

**Comment by drgrigg** [comment]
Done.
