### ISSUE TITLE
`local.css` cleanup

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-beam-piper_cosmic_computer#8]
Lots of unnecessary CSS in `local.css`:
- Remove all h# styles, they are already standardized in `core.css`
- What is the `.block` class?  That is not semantic.  If it can be removed it should be, if not it should be named according to what it styles, not the style that it produces.
- `p.sign` can be better styled as `blockquote.sign`, and remove the margins, as `<blockquote>` already has margins. `<blockquote>` requires a direct block-level descendant, which can be `<p>`.

**Comment by drgrigg** [comment]
Done. I think it's now OK?
